CREATE SEQUENCE user_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE transaction_seq
    START WITH 1
    INCREMENT BY 1;


CREATE TABLE users (
                       id BIGINT NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       name VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,

                       CONSTRAINT users_pkey
                           PRIMARY KEY (id),

                       CONSTRAINT uk_users_email
                           UNIQUE (email)
);


CREATE TABLE wallets (
                         user_id BIGINT NOT NULL,
                         balance NUMERIC(19,2) NOT NULL,

                         CONSTRAINT wallets_pkey
                             PRIMARY KEY (user_id),

                         CONSTRAINT wallets_balance_non_negative
                             CHECK (balance >= 0),

                         CONSTRAINT fk_wallet_user
                             FOREIGN KEY (user_id)
                                 REFERENCES users(id)
);


CREATE TABLE transactions (
                              id BIGINT NOT NULL,
                              amount NUMERIC(19,2) NOT NULL,
                              created_at TIMESTAMP(6) NOT NULL,
                              receiver_id BIGINT NOT NULL,
                              sender_id BIGINT NOT NULL,
                              status VARCHAR(255) NOT NULL,
                              transaction_type VARCHAR(255) NOT NULL,

                              CONSTRAINT transactions_pkey
                                  PRIMARY KEY (id),

                              CONSTRAINT transactions_amount_positive
                                  CHECK (amount > 0),

                              CONSTRAINT fk_transaction_sender
                                  FOREIGN KEY (sender_id)
                                      REFERENCES users(id),

                              CONSTRAINT fk_transaction_receiver
                                  FOREIGN KEY (receiver_id)
                                      REFERENCES users(id)
);


CREATE TABLE idempotency_records (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     created_at TIMESTAMP(6) NOT NULL,
                                     idempotency_key VARCHAR(100) NOT NULL,
                                     user_id BIGINT NOT NULL,

                                     CONSTRAINT idempotency_records_pkey
                                         PRIMARY KEY (id),

                                     CONSTRAINT uk_idempotency_user_key
                                         UNIQUE (user_id, idempotency_key)
);


CREATE INDEX idx_transactions_sender_id
    ON transactions(sender_id);

CREATE INDEX idx_transactions_receiver_id
    ON transactions(receiver_id);